### ISSUE TITLE
Merge tags from boolean traits

### ISSUE THREAD

**Issue by psugihara** [segmentio/integration-mailchimp#16]
We have a few traits of type boolean. How will these be mapped to mailchimp merge fields? I'm not currently seeing them show up at all and I'm wondering if it's because of the type.

Thanks!

**Comment by psugihara** [comment]
OK, looks like they show up as 1 if true and 0 if false (type Number).

**Comment by f2prateek** [comment]
Let's leave this open until we document it.

**Comment by hankim813** [comment]
after upgrade to 3.0 API by Mailchimp, these will show up as "true" or "false" not 1 or 0 anymore
