### ISSUE TITLE
`.email` is sometimes an array

### ISSUE THREAD

**Issue by yields** [segmentio/integration-mailchimp#26]
I'm seeing some uncaught exceptions for [`.toLowerCase()`](https://github.com/segmentio/integration-mailchimp/blob/master/lib/index.js#L79) because `.email` is sometimes an array, let me know what we should do in that case and i'll PR!

cc @hankim813 / @sperand-io

**Comment by hankim813** [comment]
ahhh @yields yeah we should make sure it's a string before using that function and if it's an array i think we should reject it since we don't want people thinking that is a good way to send email...

**Comment by f2prateek** [comment]
Yeah probably better fixed in facade I think? It could automatically just return the first email if it's an array.

**Comment by yields** [comment]
@f2prateek 

tough call for me, i don't know what's best to do here, sometimes the arrays contain more than one email, but most don't.

If i was using the integration, i would follow the docs:

<img width="650" alt="screen shot 2016-02-25 at 8 00 45 pm" src="https://cloud.githubusercontent.com/assets/1661587/13329036/860aaa2a-dbfa-11e5-97e0-e5886fc04756.png">

_But_ if there's another integration that allows arrays as email and we specify in the docs that they should send `.email` as array, then fixing in facade makes sense to me...

**Comment by f2prateek** [comment]
Yeah tricky, but I think facade should match our spec (single string email) as much as possible. 

In the case of tools that need multiple emails they could call `.proxy` instead of using `.email` directly.

I'm also pretty sure returning an array instead of a single email might be causing issues in other integrations silently.

The workaround is good for now though!

**Comment by yields** [comment]
> I'm also pretty sure returning an array instead of a single email might be causing issues in other integrations silently.

Good point, haven't thought of that at all :/
