### ISSUE TITLE
custom traits cant be longer than 10 chars

### ISSUE THREAD

**Issue by sperand-io** [segmentio/integration-mailchimp#4]
their merge fields, which we use to map custom traits, can't be longer than 10 chars.

![](https://cloudup.com/cZle45LfU_W+)

this is a bummer for users who have been sending data to other tools with traits longer than 10 chars, as they're outright incompatible with mailchimp custom fields.

so we could do one of two things, (i think?):

- add a field mapper to the UI so that customers can map any trait (of any length) to specific merge fields.

- automatically take the first 10 character substring of any trait name longer than 10 chars and match on that basis instead 

of the two, i'm not sure which i dislike less. thoughts? @amillet89 @DirtyAnalytics @harrietgrace

**Comment by daxhuiberts** [comment]
I'm the person who stumbled upon this issue with Mailchimp.
I agree with @sperand-io that it's an issue about choosing one of the lesser evils.
Of the two possible solutions, my thoughts go to the truncation solution.

**Comment by DirtyAnalytics** [comment]
I'm cool with the truncation version. 


The mapping stuff generally confuses people unless it's something really obvious like mapping an event to a pixel id like Adwords.

**Comment by zachkinloch** [comment]
What happens currently? We're planning to integrate with Mailchimp and want to be aware of any issues ahead of time, will it get automatically get truncated or rejected since the event name is longer than 10 characters?

**Comment by pauloschilling** [comment]
@zachkinloch Today Mailchimp is ignoring these traits [longer than 10 chars].

@DirtyAnalytics Are you guys planning to do something about this issue?

**Comment by DirtyAnalytics** [comment]
@pauloschilling do you agree the truncation would be best?

**Comment by pauloschilling** [comment]
Definitely! I'm totally comfortable with this solution. :)

**Comment by pauloschilling** [comment]
@f2prateek Since it was merged a few hours ago, how much time it will take to go live in production?

**Comment by f2prateek** [comment]
I'll be releasing it on Monday.

**Comment by psugihara** [comment]
Would be cool if this was documented somewhere a bit more prominently.

Maybe here? 

https://segment.com/docs/integrations/mailchimp/

**Comment by dmitry-mukhin** [comment]
I second @psugihara
